### ISSUE TITLE
Annotation use

### ISSUE THREAD

**Issue by vincentbrison** [sagix/executordecorator#3]
It is not an issue but a request for information:

I wonder if the code generation only occurs if a method which returns the interface we want to decorate is annotated ?
Currently we have to provide a method like:
```
@ImmutableExecutorDecorator public MyInterface provideMyInterface(){
    return null;
}
```

Dont you think it may be miss leading to annotate such an empty method ? It may however integrate quite good with Dagger, where you have a module providing such an interface and you only annotate the providing method. Is this how you actually using it ?

I guess its a bad idea to let the interface itself be annotated, but I wonder if there is another way of doing this.

Thanks !

**Comment by sagix** [comment]
The point is to annotate a _Dagger Module_ or a _Factory_ and not the interface itself.
Because there is some cases where you do not control the interface (it may be part of a framework or a external library)
Maybe my example is not clear. In fact you will have a Dagger module like that:
```java
@Module
class MyModule{
    @Provides @ImmutableExecutorDecorator public MyInterface provideMyInterface(Executor executor){
        return MyInterfaceDecorator(executor, new RealImplementationMyInterface());
    }
}
```
So, in a real case, the method will not return `null` but a instance of the generated decorator.

The [sample](https://github.com/sagix/executordecorator/tree/master/executordecorator-samples/src/main/java/com/nicolasmouchel/executordecorator/samples) can help you.
Feel free to update the README.md again ;)
I will add later a real example for Android.

**Comment by vincentbrison** [comment]
This is how I started to using it, but there is not mention of Dagger in the README.md (only in the tests , some classes names contain `Module`), so I was wondering. Then yes, if it is the main use case, maybe I could update the README.md with the example you just gave ;).

Thanks for the explanation.
